### ISSUE TITLE
Internet Explorer incorrectly breaks off connection each 15 seconds, the server doesn't fulfill onClose event

### ISSUE THREAD

**Issue by webspec2012** [hoaproject/Websocket#33]

**Comment by Hywan** [comment]
Excuse me, but what did you do exactly?

**Comment by webspec2012** [comment]
Sample server:

```php
date_default_timezone_set('UTC');
require_once "vendor/autoload.php";
if (!defined('HOA')) {
    die("Failed start daemon: Hoa-socket lib not found");
}

// get unique client ID
function getClientId($bucket) {
    return $bucket->getSource()->getConnection()->getCurrentNode()->getId();
}

// server run
$websocket = new Hoa\Websocket\Server(
    new Hoa\Socket\Server('tcp://0.0.0.0:3333')
);

$websocket->on('open', function ( Hoa\Core\Event\Bucket $bucket ) {

    echo 'new connection #', getClientId($bucket), "\n";

    return;
});

$websocket->on('message', function ( Hoa\Core\Event\Bucket $bucket ) {

    $data = $bucket->getData();
    echo '> message ', $data['message'], "\n";
    $bucket->getSource()->send($data['message']);
    echo '< echo', "\n";

    return;
});

$websocket->on('close', function ( Hoa\Core\Event\Bucket $bucket ) {
    echo 'connection closed #', getClientId($bucket), "\n";

    return;
});

$websocket->run();
```

Sample Client:
http://fulledu.ru/websocket/

```javascript
<input type="text" id="input" placeholder="Message…" />
<hr />
<pre id="output"></pre>

<script>
    function mySocketServer() {
        var host   = 'ws://fulledu.ru:3333';
        var socket = null;
        var input  = document.getElementById('input');
        var output = document.getElementById('output');
        var print  = function ( message ) {

            var samp       = document.createElement('samp');
            samp.innerHTML = message + '\n';
            output.appendChild(samp);

            return;
        };

        input.addEventListener('keyup', function ( evt ) {

            if(13 === evt.keyCode) {

                var msg = input.value;

                if(!msg)
                    return;

                try {

                    socket.send(msg);
                    input.value = '';
                    input.focus();
                }
                catch ( e ) {

                    console.log(e);
                }

                return;
            }
        });

        try {

            socket = new WebSocket(host);
            socket.onopen = function ( ) {

                print('connection is opened');
                input.focus();

                return;
            };
            socket.onmessage = function ( msg ) {

                print(msg.data);

                return;
            };
            socket.onclose = function ( ) {
                print('connection is closed');

                setTimeout(function(){mySocketServer()}, 1000 * 2);

                return;
            };
        }
        catch ( e ) {
            console.log(e);
        }
    }

    mySocketServer();
</script>
```

Result screenshot with Internet Explorer:
http://static.fulledu.ru/example_bug.png

onClose event not work...

**Comment by Hywan** [comment]
Which version of Internet are you using?

**Comment by Hywan** [comment]
I assign @camael24 on this one. He will try to reproduce.

**Comment by webspec2012** [comment]
"Internet Explorer 11"

The same bug can be reproduced if connection is broken off by the third party.
For example:

* At the client the Internet was gone
* Connection with the client was broken off by nginx on timeout
or etc..

**Comment by Hywan** [comment]
Is it the same issue you reported #31, #32 and #30?

**Comment by webspec2012** [comment]
Possibly it is other mistakes, for certain I can't tell.

**Comment by camael24** [comment]
I try to reproduce tomorrow :)

**Comment by camael24** [comment]
I confirm the "bug", i reproduce it on IE11

**Comment by webspec2012** [comment]
Требуется что бы событие onClose срабатывало в любом случае, если клиент был отсоединен от сервера.

**Comment by webspec2012** [comment]
It is required that the event of onClose would work anyway if the client was disconnected from the server.

**Comment by Hywan** [comment]
It's going to be difficult to debug, I don't have Windows. Any idea how could I do that?

**Comment by camael24** [comment]
With an VM ? and an demo key

**Comment by camael24** [comment]
https://www.modern.ie/fr-fr/virtualization-tools

**Comment by Hywan** [comment]
Perfect! Thanks.

**Comment by Hywan** [comment]
Here is what need to be considered.

IE sends an unsollicited `PONG` frame. The [RFC6455 says](https://tools.ietf.org/html/rfc6455#section-5.5.3):

>   A Pong frame MAY be sent unsolicited.  This serves as a
>   unidirectional heartbeat.  A response to an unsolicited Pong frame is
>   not expected.

Several implementations out there (Play, Spring, Go etc.) encountered this issue because receiving an unsollicited `PONG` was not expected and was creating a bug. In `Hoa\Websocket`, this is not the case because [we handle it as required by the RFC](https://github.com/hoaproject/Websocket/blob/7b97f1477562fe8847799ac8b193ea9afd57da4e/Connection.php#L419-L426). IE has the `fin` parameter set to 1, not 0, so this is a valid frame and we don't respond to it.

Since we don't respond, IE sends a random frame that is not a valid one. And yes, **random**, I don't receive the same frame twice.
After some searches, it seems that this is [a known bug in IE10](https://connect.microsoft.com/IE/feedback/details/804653/rfc6455-websocket-pong-frame) (not 11). To fix that, we may return a `PING`. This is what I did, but it does not fix anything. Maybe on IE10, but not on IE11.

Because the bug is still opened on IE10, we can assume this is still present in IE11.

I close this issue because I can't do anything to avoid that… The connection is [closed by the server](https://github.com/hoaproject/Websocket/blob/7b97f1477562fe8847799ac8b193ea9afd57da4e/Connection.php#L260-L265) because of the malformed/invalid message we receive after the `PONG`. IE does not fire the `CloseEvent` properly despites the server sends a valid close frame!

Sorry for that. If you find a server that handles IE11 properly, I would be glad to know them and look inside the code to see what workaround they found.
