### ISSUE TITLE
Bucket Send problem

### ISSUE THREAD

**Issue by Dirape** [hoaproject/Websocket#99]
Hello,  iam trying to save users in special room using
SplObjectStorage 
For example 
$data->room[$room_id]->attach($bucket);
foreach($data->room[$room_id] as $buck)
{

$buck->getSource()->send("new user");
}
The problem that this method send the msg each time for the same user inserted  in first line 
...
I need to save the users and send msg for each

**Comment by Hywan** [comment]
Hello,

Why are you using a `SplObjectStorage` to store objects as keys of your hashmap if, in your loop, you are only binding on the value (`$buck`)? Based on [the documentation](http://php.net/manual/en/splobjectstorage.attach.php), `$buck` must be `null` despite the implementation says the opposite. There is either a bug in the documentation, or in the implementation… anyway.

You are storing users by rooms. When you add a user to a room, you are iterating over all the other users of the same room and send a message to… the current node. You must say where the message should be sent by using the second parameter of `send`: https://github.com/hoaproject/Websocket/blob/a2a5964ed4daf971d4780476359d39be3d4ce046/Connection.php#L554-L559

The `$node` argument represent the “instance” of the user that will receive your message. It's like saying: “send this $message to $node”.

I guess `getSource` returns the server in your example, so if no `$node` is specified, it's like saying: “send this $message to the current node”: https://github.com/hoaproject/Socket/blob/705ec983534171c825e2c63a26d51b97e5de01b8/Connection/Handler.php#L249-L253

My personal recommendation is to use a particular `Node` class to represent your user, and add a `roomId` attribute on them. Read [the Customized node Section of the documentation](https://hoa-project.net/En/Literature/Hack/Websocket.html#Customized_node). So that you can use the `broadcastIf` method to send a message to a particular collection of users/nodes: https://github.com/hoaproject/Socket/blob/705ec983534171c825e2c63a26d51b97e5de01b8/Connection/Handler.php#L319.

For instance:

```php

$currentNode = …;
$predicate = function (MyNode $node) use ($currentNode) {
    return
        $currentNode !== $node && // send to everyone except me, and…
        $myNode->roomId === $node->roomId // send to every node in the same room than me.
};

$myNode->getSource()->broadcastIf($predicate, 'new user');
```

Main pros:

* The predicate can be unit tested and reused,
* `broadcastIf` already manages all the network complexity for you (if a node has been disconnected when iterating over the nodes for instance).

**Comment by Dirape** [comment]
i did it by this method
adding user to object room
` $node = $bucket->getSource()->getConnection()->getCurrentNode();
       $room->users->attach($node);`

and then on  message 
`  
    foreach($room->users as $node)
    {
   
        $bucket->getSource()->send($message,$node);

    }`
and it works !
